### ISSUE TITLE
Need some examples of orders 

### ISSUE THREAD

**Issue by dara1400** [hootnot/oandapyV20-examples#11]
I need a simple example of a pending order

**Comment by hootnot** [comment]
I need ...?

docs are pretty clear: 

- first create a limit order : http://oanda-api-v20.readthedocs.io/en/latest/endpoints/orders/ordercreate.html, see contrib.requests also for classes to simplify order construction
- http://oanda-api-v20.readthedocs.io/en/latest/contrib/orders/limitorderrequest.html
- then request the pending orders using: 
http://oanda-api-v20.readthedocs.io/en/latest/endpoints/orders/orderspending.html
- check examples: https://github.com/hootnot/oandapyV20-examples/blob/master/src/market_orders_requests.py, easy to adapt to a limitorder using the LimitOrderRequest from contrib
