### ISSUE TITLE
Modifying Trade

### ISSUE THREAD

**Issue by dara1400** [hootnot/oandapyV20-examples#12]
Is it possible to modify a trade and change it's StopLoss?

**Comment by hootnot** [comment]
http://developer.oanda.com/rest-live-v20/trade-ep/ example

use the oandapyV20 endpoints accordingly:
http://oanda-api-v20.readthedocs.io/en/latest/endpoints/trades/tradeCRCDO.html

this is the 3rd time you ask a question that is simply in the docs. It is your task to study the docs en experiment with code
