### ISSUE TITLE
Edit stoploss and takeprofit of open trade

### ISSUE THREAD

**Issue by wybren84** [hootnot/oandapyV20-examples#19]
I use the code of contrib_mo_tp_sl.py more or less to place a market order with a stop loss and take profit order. I was wondering how to change stoploss and takeprofit of an open trade?

**Comment by hootnot** [comment]
http://developer.oanda.com/rest-live-v20/order-ep/
so from the endpoints you need TradeCRCDO, see example in http://oanda-api-v20.readthedocs.io/en/latest/examples.html at the end of the file
