### ISSUE TITLE
Please add -- An example on trading using this library

### ISSUE THREAD

**Issue by developeralgo8888** [hootnot/oandapyV20-examples#4]
Is it possible to put together a small single example for trading demonstration only i.e

1. automatically connect to oanda
2. Start receiving real-time streaming data  and at the same time store the received data for further calculations in step 3 --strategy calculations . Maybe Store it in a database or somewhere that it can be pulled fast to be used algo trading calculation or backtesting etc
3. Simple strategy for demonstrations only e.g a moving average strategy  in 1 minute timeframe
4. Calculate  whether to enter market order -- buy or sell with automated TP and SL
5. Track the trade 
6. Close the trade 
7. get the portfolio update

just something simple for illustrations

**Comment by hootnot** [comment]
more examples will follow on short term, a trading example will be part of it

**Comment by developeralgo8888** [comment]
Thanks , still waiting for the above example . When do you think you will be able to have trading example  ready
